Sonarqube filter params sdk 13.x
JupiterOne/graph-sonarqube pull request #54
Opened 2024-07-24 13:53 UTC by Bharatkk-metron

filter params added

2024-07-30 11:19 UTC, suraj-metron requested changes

2024-07-30 11:19 UTC, suraj-metron commented on yarn.lock
is this file required to be modified?

2024-07-30 11:19 UTC, suraj-metron commented on tsconfig.json
> +    "lib": ["dom"]
Why this change?

2024-07-30 11:22 UTC, Bharatkk-metron commented on tsconfig.json
> +    "lib": ["dom"]
Without this change yarn test:ci was failing. Was not able to find some global variables. Which was basically coming from Dom Library.

2024-07-30 11:23 UTC, Bharatkk-metron commented on yarn.lock
yes. I think since we have updated the version.

2024-07-30 11:29 UTC, Bharatkk-metron commented on package-lock.json
Same as a yarn lock. Since we updated the package versions, we can have this.

2024-07-30 11:33 UTC, Bharatkk-metron commented on .env.example
> +# JUST FOR INFO:
removed.

2024-07-30 11:35 UTC, suraj-metron commented on package-lock.json
ok

2024-07-30 11:36 UTC, suraj-metron commented on .env.example
> +# JUST FOR INFO:
Ok

2024-07-30 11:36 UTC, suraj-metron commented on yarn.lock
Ok

2024-07-30 11:36 UTC, suraj-metron commented on tsconfig.json
> +    "lib": ["dom"]
Okay

2024-07-30 11:36 UTC, suraj-metron approved these changes

2024-07-31 22:29 UTC, RonaldEAM requested changes

2024-07-31 22:29 UTC, RonaldEAM commented on src/instanceConfigFields.ts
> +  },
```suggestion
  findingSeverities: {
    type: 'string',
    mask: false,
    optional: true,
  },
  findingStatus: {
    type: 'string',
    mask: false,
    optional: true,
  },
  findingsIngestSinceDays: {
    type: 'string',
    mask: false,
    optional: true,
  },
  findingTypes: {
    type: 'string',
    mask: false,
    optional: true,
  },
```

2024-07-31 22:29 UTC, RonaldEAM commented on .env.example
> +CREATED_IN_LAST=10d # default value is 10 days
Please change this name to `FINDINGS_INGEST_SINCE_DAYS` and make it a number where options are 90, 180, 275, 365 (days). Then you can convert those to the format sonarqube expects when you send the request. This way we are not attached to using their format in our config.
Github example:
![image](https://github.com/user-attachments/assets/158822ca-d9af-436a-8468-caa196c6e7e7)

2024-07-31 22:29 UTC, RonaldEAM commented on src/steps/finding/index.ts
> +}
Can you validate the config for this in validateInvocation and parse it there instead? So when this step starts the config value is ready to use 
Example: https://github.com/JupiterOne/integrations/blob/main/graph/graph-gitlab/src/config.ts#L70

2024-07-31 22:29 UTC, RonaldEAM commented on src/steps/finding/index.ts
> +      for (const severity of severities) {
👍

2024-07-31 22:29 UTC, RonaldEAM commented on src/steps/finding/index.ts
> +}
Same as with severities, it should be validated and parsed in validateInvocation

2024-07-31 22:29 UTC, RonaldEAM commented on src/types.ts
> +  types?: string;
```suggestion
  findingSeverities?: string[];
  findingStatus?: string[];
  findingsIngestSinceDays?: number;
  findingTypes?: string[];
```

2024-07-31 22:50 UTC, RonaldEAM commented on src/steps/finding/index.ts
> +  const filterParams = getFilterParams(instance.config);
can you make sure we don't send any of these if they come undefined in `instanceConfig` instead of using defaults? so only new instances use those filters

2024-08-05 10:37 UTC, Bharatkk-metron commented on src/steps/finding/index.ts
> +  const filterParams = getFilterParams(instance.config);
I have removed the function getSeverities. For getFilterParams, we will use the values only if they are present; otherwise, we will not include anything in filterParams.

2024-08-05 21:19 UTC, RonaldEAM requested changes

2024-08-05 21:19 UTC, RonaldEAM commented on src/steps/finding/index.ts
> +    `${findingsIngestSinceDays || DEFAULT_FINDING_INGEST_SINCE_DAYS}d`;
we should also not filter by this if there's no config set for it

2024-08-07 20:55 UTC, RonaldEAM approved these changes

2024-08-07 20:55 UTC, merged